# 固件的名字
TARGET = empty

# 目录变量，用户不用修改
ROOT_DIR     = ../../..
EXAMPLE_DIR  = ../..
PROJECT_DIR  = ..
USER_SRC_DIR = .

C_SOURCES =  \
main.c \

-include $(PROJECT_DIR)/hal_module.conf
-include $(ROOT_DIR)/RULE.mk
